events {
    worker_connections 1024;
}

http {
    upstream backend {
        # === Round Robin (закомментировано) ===
        # server app:8080;
        # server app:8080;
        # server app:8080;

        # === Least Connections (активировано) ===
        least_conn;
        server app:8080;
        server app:8080;
        server app:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}