create schema if not exists currency;

create table if not exists currency.users
(
    id integer  Generated by default as identity primary key,
    "name" varchar not null,
    surname varchar not null,
    nickname varchar not null unique,
    email varchar not null unique,
    password varchar not null
);

create table if not exists currency.roles
(
    user_id int not null,
    "role" varchar not null,
    primary key (user_id,"role"),
    constraint fk_users_roles_users foreign key (user_id) references users (id) on delete cascade on update no action
);